sudo: require
dist: bionic
language: csharp
mono: none
dotnet: 5.0
services: docker
before_install:
  - cd RestWithASPNETUdemy/
  - echo "We are ni the right folder!"
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag rest-with-asp-net-udemy:$TRAVIS_JOB_ID $DOCKER_USERNAME/rest-with-asp-net-udemy:$TRAVIS_JOB_ID;
    docker tag rest-with-asp-net-udemy-db:$TRAVIS_JOB_ID $DOCKER_USERNAME/rest-with-asp-net-udemy-db:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/rest-with-asp-net-udemy:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/rest-with-asp-net-udemy-db:$TRAVIS_JOB_ID;
on:
  branch: master
notifications:
  email: false